query getTodos {
    todos{
      id
      text
      isComplete
    }
  }

mutation deleteTodo($id: String!) {
    deleteTodo(id: $id){
       id
       text
       isComplete
    }
}

mutation editTodo($id: String!, $text: String!) {
    updateTodoText(id: $id, text: $text){
       id
       text
       isComplete
    }
}