/* This file is autogenerated, please don't change it manually! */
export type Maybe<T> = T | null;

/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string,
  String: string,
  Boolean: boolean,
  Int: number,
  Float: number,
};

export type Mutation = {
   __typename?: 'Mutation',
  addTodo?: Maybe<Todo>,
  deleteTodo?: Maybe<Todo>,
  updateTodoText?: Maybe<Todo>,
  markTodoComplete?: Maybe<Todo>,
};


export type MutationAddTodoArgs = {
  text: Scalars['String']
};


export type MutationDeleteTodoArgs = {
  id: Scalars['String']
};


export type MutationUpdateTodoTextArgs = {
  id: Scalars['String'],
  text: Scalars['String']
};


export type MutationMarkTodoCompleteArgs = {
  id: Scalars['String']
};

export type Query = {
   __typename?: 'Query',
  todo?: Maybe<Todo>,
  todos?: Maybe<Array<Maybe<Todo>>>,
  activeTodos?: Maybe<Array<Maybe<Todo>>>,
  completedTodos?: Maybe<Array<Maybe<Todo>>>,
};


export type QueryTodoArgs = {
  id: Scalars['String']
};

export type Todo = {
   __typename?: 'Todo',
  id: Scalars['String'],
  text: Scalars['String'],
  isComplete: Scalars['Boolean'],
};
